name: Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: xcodebuild test -project sprinter-ios.xcodeproj -scheme sprinter-ios -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' build test
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
