name: CI

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    runs-on: macos-latest
    if: ${{ github.event.label.name == 'CI' }}
    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run: 
        # xcodebuild test -project sprinter-ios.xcodeproj -scheme sprinter-ios -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' build test
        xcodebuild build \
        -scheme "sprinter-ios"
        -clonedSourcePackageDirPath SourcePackages \
        -destination "platform=iOS Simulator,name=iPhone 14"
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
